### ISSUE TITLE
Deprecated Variable

### ISSUE THREAD

**Issue by ywk991112** [leomao/pika-vim#4]
[deoplete] g:deoplete#sources is deprecated variable. Please use deoplete#custom#option() instead.
原本hao字，拿掉了
```
let g:deoplete#sources = {}
let g:deoplete#sources._ = []
```
就好了

**Comment by leomao** [comment]
Marked as won't fix because  I am not going to maintain vim configuration anymore. I move to neovim.

**Comment by leomao** [comment]
Marked as won't fix because  I am not going to maintain vim configuration anymore. I move to neovim.
